name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=app.ico gui.py
    
    - name: Create Release ZIP
      run: |
        powershell Compress-Archive -Path "dist/*","version.json","translations.json" -DestinationPath CuttingOptimizerPro.zip
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          CuttingOptimizerPro.zip
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}